### ISSUE TITLE
I can't delete all of the deactivated profiles

### ISSUE THREAD

**Issue by drwalidsaib** [locmai0808/Multiple-Tools-for-Facebook#7]
Hi there,
Thanks for this wonderful extension...

I'm facing a lot of problems but first things first,

some of my old friends get their profiles deactivated due to Facebook
 policies and so on
and if i try to delete them, it said that an error occurred, any suggestions?

![Screenshot_9](https://user-images.githubusercontent.com/40124999/62816373-fcb9ee00-bb1d-11e9-9706-c7d5f801b29e.png)

by the way...how can i suggest for some modifications for the extension?

**Comment by locmai0808** [comment]
Hello, It is actually not a bug.

This feature uses 2 different APIs to delete deactivate friends...and if it say could not delete, then Facebook doesn't let you delete them. 

You can always suggest some modifications on this git repo :)
